[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --access-logfile - --error-logfile -"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[services.app]
source = "."
watch = ["app/", "alembic/", "pyproject.toml"]

[env]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO" 