[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.app]
source = "."
watch = ["app/", "alembic/", "pyproject.toml"]
