"""Add string constraints and indexes for performance

Revision ID: 2d4f350656a8
Revises: 54ef7027dfd6
Create Date: 2025-06-09 16:44:49.984287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4f350656a8'
down_revision = '54ef7027dfd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vote_participation_user_id_fkey'), 'vote_participation', type_='foreignkey')
    op.drop_constraint(op.f('vote_participation_restaurant_id_fkey'), 'vote_participation', type_='foreignkey')
    op.drop_constraint(op.f('vote_participation_vote_session_id_fkey'), 'vote_participation', type_='foreignkey')
    op.create_foreign_key(None, 'vote_participation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote_participation', 'vote_session', ['vote_session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote_participation', 'restaurant', ['restaurant_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_vote_session_auto_close', 'vote_session', ['auto_close_at'], unique=False)
    op.create_index('ix_vote_session_created_by', 'vote_session', ['created_by_user_id'], unique=False)
    op.create_index('ix_vote_session_status', 'vote_session', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vote_session_status', table_name='vote_session')
    op.drop_index('ix_vote_session_created_by', table_name='vote_session')
    op.drop_index('ix_vote_session_auto_close', table_name='vote_session')
    op.drop_constraint(None, 'vote_participation', type_='foreignkey')
    op.drop_constraint(None, 'vote_participation', type_='foreignkey')
    op.drop_constraint(None, 'vote_participation', type_='foreignkey')
    op.create_foreign_key(op.f('vote_participation_vote_session_id_fkey'), 'vote_participation', 'vote_session', ['vote_session_id'], ['id'])
    op.create_foreign_key(op.f('vote_participation_restaurant_id_fkey'), 'vote_participation', 'restaurant', ['restaurant_id'], ['id'])
    op.create_foreign_key(op.f('vote_participation_user_id_fkey'), 'vote_participation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
