"""Remove old vote table

Revision ID: 54ef7027dfd6
Revises: 2d8201e94556
Create Date: 2025-06-09 15:53:33.621218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54ef7027dfd6'
down_revision = '2d8201e94556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_id'), table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('vote_restaurant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('vote_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vote_pkey'))
    )
    op.create_index(op.f('ix_vote_id'), 'vote', ['id'], unique=False)
    # ### end Alembic commands ###
