"""Add weighted voting system to vote sessions

Revision ID: 810b3300f3e1
Revises: d6344313dac7
Create Date: 2025-06-08 12:32:21.072607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810b3300f3e1'
down_revision = 'd6344313dac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('vote_participation', sa.Column('vote_sequence', sa.Integer(), nullable=True))
    op.add_column('vote_participation', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('vote_session', sa.Column('votes_per_user', sa.Integer(), nullable=True))
    op.add_column('vote_session', sa.Column('auto_close_at', sa.DateTime(), nullable=True))

    # Update existing data with default values
    # For vote_participation: set vote_sequence=1, weight=1.0 for existing records
    op.execute("UPDATE vote_participation SET vote_sequence = 1, weight = 1.0 WHERE vote_sequence IS NULL")

    # For vote_session: set votes_per_user=1 for existing records
    op.execute("UPDATE vote_session SET votes_per_user = 1 WHERE votes_per_user IS NULL")

    # Now make the columns NOT NULL
    op.alter_column('vote_participation', 'vote_sequence', nullable=False)
    op.alter_column('vote_participation', 'weight', nullable=False)
    op.alter_column('vote_session', 'votes_per_user', nullable=False)

    # Update constraints
    op.drop_constraint(op.f('unique_user_vote_per_session'), 'vote_participation', type_='unique')
    op.create_unique_constraint('unique_user_vote_sequence_per_session', 'vote_participation', ['vote_session_id', 'user_id', 'vote_sequence'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_session', 'auto_close_at')
    op.drop_column('vote_session', 'votes_per_user')
    op.drop_constraint('unique_user_vote_sequence_per_session', 'vote_participation', type_='unique')
    op.create_unique_constraint(op.f('unique_user_vote_per_session'), 'vote_participation', ['vote_session_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vote_participation', 'weight')
    op.drop_column('vote_participation', 'vote_sequence')
    # ### end Alembic commands ###
