"""Add weighted voting system to vote sessions

Revision ID: 810b3300f3e1
Revises: d6344313dac7
Create Date: 2025-06-08 12:32:21.072607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810b3300f3e1'
down_revision = 'd6344313dac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_participation', sa.Column('vote_sequence', sa.Integer(), nullable=False))
    op.add_column('vote_participation', sa.Column('weight', sa.Float(), nullable=False))
    op.drop_constraint(op.f('unique_user_vote_per_session'), 'vote_participation', type_='unique')
    op.create_unique_constraint('unique_user_vote_sequence_per_session', 'vote_participation', ['vote_session_id', 'user_id', 'vote_sequence'])
    op.add_column('vote_session', sa.Column('votes_per_user', sa.Integer(), nullable=False))
    op.add_column('vote_session', sa.Column('auto_close_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_session', 'auto_close_at')
    op.drop_column('vote_session', 'votes_per_user')
    op.drop_constraint('unique_user_vote_sequence_per_session', 'vote_participation', type_='unique')
    op.create_unique_constraint(op.f('unique_user_vote_per_session'), 'vote_participation', ['vote_session_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vote_participation', 'weight')
    op.drop_column('vote_participation', 'vote_sequence')
    # ### end Alembic commands ###
