"""Add vote session architecture

Revision ID: d6344313dac7
Revises: 001
Create Date: 2025-06-08 00:10:23.141302

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d6344313dac7"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vote_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "CLOSED", name="votesessionstatus"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vote_session_id"), "vote_session", ["id"], unique=False)
    op.create_table(
        "vote_participation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vote_session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.Column("voted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vote_session_id"],
            ["vote_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "vote_session_id", "user_id", name="unique_user_vote_per_session"
        ),
    )
    op.create_index(
        op.f("ix_vote_participation_id"), "vote_participation", ["id"], unique=False
    )
    op.create_table(
        "vote_session_restaurants",
        sa.Column("vote_session_id", sa.Integer(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vote_session_id"],
            ["vote_session.id"],
        ),
        sa.PrimaryKeyConstraint("vote_session_id", "restaurant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vote_session_restaurants")
    op.drop_index(op.f("ix_vote_participation_id"), table_name="vote_participation")
    op.drop_table("vote_participation")
    op.drop_index(op.f("ix_vote_session_id"), table_name="vote_session")
    op.drop_table("vote_session")
    # ### end Alembic commands ###
